### ISSUE TITLE
Some minor changes

### ISSUE THREAD

**Issue by bramley** [bradallenfisher/phplist-cosign#1]
I'm fine with you owning this plugin. A few comments:
- Can you rename the repository to phplist-plugin-cosign so that it is consistent with other phplist plugins.
- I saw some references to COSIGN_SERVICE but didn't really understand it. Doesn't cosign remove the cookie when someone actually logs-out of cosign?
- Would it work if the setting for the logout url is only the base url, with HTTP_HOST added dynamically, or is it likely other people would have a different structure to the url?
- Can you make the indentation consistent, 4 characters not 2.
- remove the two const lines at the beginning of the class. I copied from another plugin and these are not relevant. But you might want to add your own versioning as that will appear on the phplist plugins page

```
public $version = 'xxx';
```

**Comment by baf139** [comment]
Great. I will update asap. Meetings for the next couple of hours.

**Comment by bramley** [comment]
I found an example of logging-out  http://www.lancaster.ac.uk/iss/tsg/cosign/using_php.html and you have implemented what is in that example, so please ignore the second and third points.

**Comment by baf139** [comment]
I will actually put a comment in to explain what is in that doc. Mainly:
If you don't clear the local session cookie and only redirect the browser to the CoSign logout URL, the CoSign session will still be logged out, but the local session will still be valid for about a minute because the CoSign filter caches the credentials.

For point 3 if have an idea I will do a new commit and see what you think. 

Thanks

**Comment by baf139** [comment]
@bramley I think i have cleaned this up to spec :+1: 

If I missed anything let me know.

Otherwise close this issue. 

Thanks!
